project:
  type: website
  output-dir: docs
website:
  title: "Hfiro.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: cosmo
      dark: darkly

editor: visual

